package session

import (
	"fmt"
	"time"
)

func WrapReportHTML(title string, contentHTML string, sessionID string) string {
	return fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>%s</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; color: #333; }
.report-header { border-bottom: 3px solid #2196f3; padding-bottom: 15px; margin-bottom: 20px; }
.report-header h1 { color: #1976d2; margin: 0; }
.report-header .meta { color: #999; font-size: 12px; margin-top: 5px; }
.report-content { line-height: 1.6; }
.report-footer { border-top: 1px solid #eee; padding-top: 10px; margin-top: 30px; font-size: 12px; color: #999; }
table { border-collapse: collapse; width: 100%%; margin: 15px 0; }
th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
th { background-color: #f5f5f5; }
tr:nth-child(even) { background-color: #fafafa; }
</style>
</head>
<body>
<div class="report-header">
<h1>%s</h1>
<div class="meta">Session: %s | Generated: %s</div>
</div>
<div class="report-content">%s</div>
<div class="report-footer">Generated by Phoenix Agent &copy; %d</div>
</body>
</html>`, title, title, sessionID, time.Now().Format("2006-01-02 15:04:05"), contentHTML, time.Now().Year())
}
