// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpc/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentSn       string                 `protobuf:"bytes,1,opt,name=agent_sn,json=agentSn,proto3" json:"agent_sn,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCallRequest) Reset() {
	*x = AgentCallRequest{}
	mi := &file_rpc_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCallRequest) ProtoMessage() {}

func (x *AgentCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCallRequest.ProtoReflect.Descriptor instead.
func (*AgentCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentCallRequest) GetAgentSn() string {
	if x != nil {
		return x.AgentSn
	}
	return ""
}

func (x *AgentCallRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AgentCallRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentCallRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AgentCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCallResponse) Reset() {
	*x = AgentCallResponse{}
	mi := &file_rpc_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCallResponse) ProtoMessage() {}

func (x *AgentCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCallResponse.ProtoReflect.Descriptor instead.
func (*AgentCallResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentCallResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentCallResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AgentCallResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_rpc_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_agent_proto_rawDescGZIP(), []int{2}
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sn            string                 `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_rpc_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_rpc_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfo) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_rpc_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

var File_rpc_proto_agent_proto protoreflect.FileDescriptor

const file_rpc_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15rpc/proto/agent.proto\x12\x03rpc\"\x7f\n" +
	"\x10AgentCallRequest\x12\x19\n" +
	"\bagent_sn\x18\x01 \x01(\tR\aagentSn\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"`\n" +
	"\x11AgentCallResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\"\x13\n" +
	"\x11ListAgentsRequest\"\x8d\x01\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02sn\x18\x02 \x01(\tR\x02sn\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"<\n" +
	"\x12ListAgentsResponse\x12&\n" +
	"\x06agents\x18\x01 \x03(\v2\x0e.rpc.AgentInfoR\x06agents2\x8c\x01\n" +
	"\fAgentService\x12=\n" +
	"\n" +
	"StreamCall\x12\x15.rpc.AgentCallRequest\x1a\x16.rpc.AgentCallResponse0\x01\x12=\n" +
	"\n" +
	"ListAgents\x12\x16.rpc.ListAgentsRequest\x1a\x17.rpc.ListAgentsResponseB'Z%github.com/phoenix-agent-go/rpc/protob\x06proto3"

var (
	file_rpc_proto_agent_proto_rawDescOnce sync.Once
	file_rpc_proto_agent_proto_rawDescData []byte
)

func file_rpc_proto_agent_proto_rawDescGZIP() []byte {
	file_rpc_proto_agent_proto_rawDescOnce.Do(func() {
		file_rpc_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_agent_proto_rawDesc), len(file_rpc_proto_agent_proto_rawDesc)))
	})
	return file_rpc_proto_agent_proto_rawDescData
}

var file_rpc_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_proto_agent_proto_goTypes = []any{
	(*AgentCallRequest)(nil),   // 0: rpc.AgentCallRequest
	(*AgentCallResponse)(nil),  // 1: rpc.AgentCallResponse
	(*ListAgentsRequest)(nil),  // 2: rpc.ListAgentsRequest
	(*AgentInfo)(nil),          // 3: rpc.AgentInfo
	(*ListAgentsResponse)(nil), // 4: rpc.ListAgentsResponse
}
var file_rpc_proto_agent_proto_depIdxs = []int32{
	3, // 0: rpc.ListAgentsResponse.agents:type_name -> rpc.AgentInfo
	0, // 1: rpc.AgentService.StreamCall:input_type -> rpc.AgentCallRequest
	2, // 2: rpc.AgentService.ListAgents:input_type -> rpc.ListAgentsRequest
	1, // 3: rpc.AgentService.StreamCall:output_type -> rpc.AgentCallResponse
	4, // 4: rpc.AgentService.ListAgents:output_type -> rpc.ListAgentsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_proto_agent_proto_init() }
func file_rpc_proto_agent_proto_init() {
	if File_rpc_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_agent_proto_rawDesc), len(file_rpc_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_agent_proto_goTypes,
		DependencyIndexes: file_rpc_proto_agent_proto_depIdxs,
		MessageInfos:      file_rpc_proto_agent_proto_msgTypes,
	}.Build()
	File_rpc_proto_agent_proto = out.File
	file_rpc_proto_agent_proto_goTypes = nil
	file_rpc_proto_agent_proto_depIdxs = nil
}
