// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpc/proto/data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_rpc_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_rpc_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ChatResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type GetDatasourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasourceRequest) Reset() {
	*x = GetDatasourceRequest{}
	mi := &file_rpc_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasourceRequest) ProtoMessage() {}

func (x *GetDatasourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasourceRequest.ProtoReflect.Descriptor instead.
func (*GetDatasourceRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetDatasourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDatasourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasourceResponse) Reset() {
	*x = GetDatasourceResponse{}
	mi := &file_rpc_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasourceResponse) ProtoMessage() {}

func (x *GetDatasourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasourceResponse.ProtoReflect.Descriptor instead.
func (*GetDatasourceResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *GetDatasourceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDatasourceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDatasourceResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetDatasourceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_rpc_proto_data_proto protoreflect.FileDescriptor

const file_rpc_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x14rpc/proto/data.proto\x12\x03rpc\"a\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"[\n" +
	"\fChatResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\"&\n" +
	"\x14GetDatasourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x15GetDatasourceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\x84\x01\n" +
	"\vDataService\x12-\n" +
	"\x04Chat\x12\x10.rpc.ChatRequest\x1a\x11.rpc.ChatResponse0\x01\x12F\n" +
	"\rGetDatasource\x12\x19.rpc.GetDatasourceRequest\x1a\x1a.rpc.GetDatasourceResponseB'Z%github.com/phoenix-agent-go/rpc/protob\x06proto3"

var (
	file_rpc_proto_data_proto_rawDescOnce sync.Once
	file_rpc_proto_data_proto_rawDescData []byte
)

func file_rpc_proto_data_proto_rawDescGZIP() []byte {
	file_rpc_proto_data_proto_rawDescOnce.Do(func() {
		file_rpc_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_data_proto_rawDesc), len(file_rpc_proto_data_proto_rawDesc)))
	})
	return file_rpc_proto_data_proto_rawDescData
}

var file_rpc_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_proto_data_proto_goTypes = []any{
	(*ChatRequest)(nil),           // 0: rpc.ChatRequest
	(*ChatResponse)(nil),          // 1: rpc.ChatResponse
	(*GetDatasourceRequest)(nil),  // 2: rpc.GetDatasourceRequest
	(*GetDatasourceResponse)(nil), // 3: rpc.GetDatasourceResponse
}
var file_rpc_proto_data_proto_depIdxs = []int32{
	0, // 0: rpc.DataService.Chat:input_type -> rpc.ChatRequest
	2, // 1: rpc.DataService.GetDatasource:input_type -> rpc.GetDatasourceRequest
	1, // 2: rpc.DataService.Chat:output_type -> rpc.ChatResponse
	3, // 3: rpc.DataService.GetDatasource:output_type -> rpc.GetDatasourceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_data_proto_init() }
func file_rpc_proto_data_proto_init() {
	if File_rpc_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_data_proto_rawDesc), len(file_rpc_proto_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_data_proto_goTypes,
		DependencyIndexes: file_rpc_proto_data_proto_depIdxs,
		MessageInfos:      file_rpc_proto_data_proto_msgTypes,
	}.Build()
	File_rpc_proto_data_proto = out.File
	file_rpc_proto_data_proto_goTypes = nil
	file_rpc_proto_data_proto_depIdxs = nil
}
